### ISSUE TITLE
关于a标签中间的链接未修改的问题

### ISSUE THREAD

**Issue by SunnyHaze** [jzzzzh/jzzzzh#1]
左边的github status图的超链接仍然定向到sunnyhaze的仓库，别忘了修改成自己的😆

**Comment by jzzzzh** [comment]
麻，，没仔细看）👌

从 Windows 版邮件发送

发件人: Xiaochen Ma
发送时间: 2022年4月15日 0:40
收件人: jzzzzh/jzzzzh
抄送: Subscribed
主题: [jzzzzh/jzzzzh] 关于a标签中间的链接未修改的问题 (Issue #1)

左边的github status图的超链接仍然定向到sunnyhaze的仓库，别忘了修改成自己的😆

**Comment by jzzzzh** [comment]
麻

**Comment by SunnyHaze** [comment]
细
